[project]
name = "my-local-ai-environment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=26.1.0",
    "fastmcp>=3.0.0b",
]
